-- V3__seed_artistas.sql
-- Artistas reais confirmados no São João de Campina Grande 2026

INSERT INTO artistas (nome, genero_musical, bio, instagram) VALUES
                                                                ('Dominguinho', 'Forró', 'Atração confirmada no Maior São João do Mundo 2026.', '@dominguinho'),
                                                                ('Solange Almeida', 'Forró', 'Atração confirmada no Maior São João do Mundo 2026.', '@solangealmeida'),
                                                                ('Limão com Mel', 'Forró', 'Atração confirmada no Maior São João do Mundo 2026.', '@limaocommel'),
                                                                ('Brasas do Forró', 'Forró', 'Atração confirmada no Maior São João do Mundo 2026.', '@brasasdoforro'),
                                                                ('À Vontade', 'Forró', 'Atração confirmada no Maior São João do Mundo 2026.', '@avontade'),
                                                                ('Dorgival Dantas', 'Forró', 'Atração confirmada no Maior São João do Mundo 2026.', '@dorgivaldantas'),
                                                                ('Samya Maia', 'Forró', 'Atração confirmada no Maior São João do Mundo 2026.', '@samyamaia'),
                                                                ('Mikael Santos', 'Piseiro', 'Atração confirmada no Maior São João do Mundo 2026.', '@mikaelsantos'),
                                                                ('Wesley Safadão', 'Forró', 'Atração confirmada no Maior São João do Mundo 2026.', '@wesleysafadao'),
                                                                ('Eric Land', 'Forró', 'Atração confirmada no Maior São João do Mundo 2026.', '@ericland'),
                                                                ('Marcynho Sensação', 'Piseiro', 'Atração confirmada no Maior São João do Mundo 2026.', '@marcynhosensacao'),
                                                                ('Deanzinho', 'Piseiro', 'Atração confirmada no Maior São João do Mundo 2026.', '@deanzinho'),
                                                                ('Henrique & Juliano', 'Sertanejo', 'Atração confirmada no Maior São João do Mundo 2026.', '@henriqueejuliano'),
                                                                ('Walkyria Santos', 'Forró', 'Atração confirmada no Maior São João do Mundo 2026.', '@walkyriasantos'),
                                                                ('Bia Frazzo', 'Forró', 'Atração confirmada no Maior São João do Mundo 2026.', '@biafrazzo'),
                                                                ('Nathan Vinícius', 'Forró', 'Atração confirmada no Maior São João do Mundo 2026.', '@nathanvinicius'),
                                                                ('Natanzinho Lima', 'Forró', 'Atração confirmada no Maior São João do Mundo 2026.', '@natanzinholima'),
                                                                ('Raphaela Santos', 'Brega', 'Atração confirmada no Maior São João do Mundo 2026.', '@raphaelasantos'),
                                                                ('Tarcísio do Acordeon', 'Forró', 'Atração confirmada no Maior São João do Mundo 2026.', '@tarcisiodoacordeon'),
                                                                ('Gitana Pimentel', 'Forró', 'Atração confirmada no Maior São João do Mundo 2026.', '@gitanapimentel'),
                                                                ('Kelly Patrícia', 'Católico', 'Atração confirmada no Maior São João do Mundo 2026.', '@kellypatricia'),
                                                                ('Ana Clara Rocha', 'Católico', 'Atração confirmada no Maior São João do Mundo 2026.', '@anaclararocha'),
                                                                ('Ítalo', 'Católico', 'Atração confirmada no Maior São João do Mundo 2026.', '@italo'),
                                                                ('Padre Nilson', 'Católico', 'Atração confirmada no Maior São João do Mundo 2026.', '@padrenilson'),
                                                                ('Léo Magalhães', 'Sertanejo', 'Atração confirmada no Maior São João do Mundo 2026.', '@leomagalhaes'),
                                                                ('Magníficos', 'Forró', 'Atração confirmada no Maior São João do Mundo 2026.', '@magnificos'),
                                                                ('Matheus Fernandes', 'Forró', 'Atração confirmada no Maior São João do Mundo 2026.', '@matheusfernandes'),
                                                                ('Matheuzin', 'Forró', 'Atração confirmada no Maior São João do Mundo 2026.', '@matheuzin'),
                                                                ('Matuê', 'Trap', 'Atração confirmada no Maior São João do Mundo 2026.', '@matue'),
                                                                ('Jonas Esticado', 'Forró', 'Atração confirmada no Maior São João do Mundo 2026.', '@jonasesticado'),
                                                                ('Cavaleiros do Forró', 'Forró', 'Atração confirmada no Maior São João do Mundo 2026.', '@cavaleirosdoforro'),
                                                                ('Karkará', 'Forró', 'Atração confirmada no Maior São João do Mundo 2026.', '@karkara'),
                                                                ('Marisa Monte', 'MPB', 'Atração confirmada no Maior São João do Mundo 2026.', '@marisamonte'),
                                                                ('Gegê Bismarck', 'Forró', 'Atração confirmada no Maior São João do Mundo 2026.', '@gegebismarck'),
                                                                ('Tito', 'Forró', 'Atração confirmada no Maior São João do Mundo 2026.', '@tito'),
                                                                ('Alexandre Tan', 'Forró', 'Atração confirmada no Maior São João do Mundo 2026.', '@alexandretan'),
                                                                ('Henry Freitas', 'Forró', 'Atração confirmada no Maior São João do Mundo 2026.', '@henryfreitas'),
                                                                ('Mari Fernandez', 'Forró', 'Atração confirmada no Maior São João do Mundo 2026.', '@marifernandez'),
                                                                ('Ávine Vinny', 'Forró', 'Atração confirmada no Maior São João do Mundo 2026.', '@avinevinny'),
                                                                ('Lipe Lucena', 'Forró', 'Atração confirmada no Maior São João do Mundo 2026.', '@lipelucena'),
                                                                ('Roberto Carlos', 'MPB', 'Atração confirmada no Maior São João do Mundo 2026.', '@robertocarlosoficial'),
                                                                ('Cavalo de Pau', 'Forró', 'Atração confirmada no Maior São João do Mundo 2026.', '@cavalodepau'),
                                                                ('Juarez', 'Forró', 'Atração confirmada no Maior São João do Mundo 2026.', '@juarez'),
                                                                ('William Sanfona', 'Forró', 'Atração confirmada no Maior São João do Mundo 2026.', '@williamsanfona'),
                                                                ('Thiago Brado', 'Católico', 'Atração confirmada no Maior São João do Mundo 2026.', '@thiagobrado'),
                                                                ('Teto Fonseca', 'Forró', 'Atração confirmada no Maior São João do Mundo 2026.', '@tetofonseca'),
                                                                ('Menos é Mais', 'Pagode', 'Atração confirmada no Maior São João do Mundo 2026.', '@grupomenosemais'),
                                                                ('Léo Foguete', 'Forró', 'Atração confirmada no Maior São João do Mundo 2026.', '@leofoguete'),
                                                                ('Michelle Andrade', 'Forró', 'Atração confirmada no Maior São João do Mundo 2026.', '@michelleandrade'),
                                                                ('Jonny Garotinho', 'Forró', 'Atração confirmada no Maior São João do Mundo 2026.', '@jonnygarotinho'),
                                                                ('Matheus & Kauan', 'Sertanejo', 'Atração confirmada no Maior São João do Mundo 2026.', '@matheusekauan'),
                                                                ('Calcinha Preta', 'Forró', 'Atração confirmada no Maior São João do Mundo 2026.', '@calcinhapreta'),
                                                                ('Grelo', 'Forró', 'Atração confirmada no Maior São João do Mundo 2026.', '@grelo'),
                                                                ('Mexe Ville', 'Forró', 'Atração confirmada no Maior São João do Mundo 2026.', '@mexeville'),
                                                                ('Iguinho e Lulinha', 'Forró', 'Atração confirmada no Maior São João do Mundo 2026.', '@iguinhoelulinha'),
                                                                ('Zé Cantor', 'Forró', 'Atração confirmada no Maior São João do Mundo 2026.', '@zecantor'),
                                                                ('Manim Vaqueiro', 'Forró', 'Atração confirmada no Maior São João do Mundo 2026.', '@manimvaqueiro'),
                                                                ('Fabiano Guimarães', 'Forró', 'Atração confirmada no Maior São João do Mundo 2026.', '@fabianoguimaraes'),
                                                                ('Fagner', 'MPB', 'Atração confirmada no Maior São João do Mundo 2026.', '@fagner'),
                                                                ('Garota Safada', 'Forró', 'Atração confirmada no Maior São João do Mundo 2026.', '@garotasafada'),
                                                                ('Ton Oliveira', 'Forró', 'Atração confirmada no Maior São João do Mundo 2026.', '@tonoliveira'),
                                                                ('Bob Léo', 'Forró', 'Atração confirmada no Maior São João do Mundo 2026.', '@bobleo'),
                                                                ('Fernandinha', 'Forró', 'Atração confirmada no Maior São João do Mundo 2026.', '@fernandinha'),
                                                                ('Samyra Show', 'Forró', 'Atração confirmada no Maior São João do Mundo 2026.', '@samyrashow'),
                                                                ('Amazan', 'Forró', 'Atração confirmada no Maior São João do Mundo 2026.', '@amazan'),
                                                                ('Raphael Moura', 'Forró', 'Atração confirmada no Maior São João do Mundo 2026.', '@raphaelmoura'),
                                                                ('Amanda Rainha da Farra', 'Forró', 'Atração confirmada no Maior São João do Mundo 2026.', '@amandarainhadafarra'),
                                                                ('Eliane', 'Forró', 'Atração confirmada no Maior São João do Mundo 2026.', '@eliane'),
                                                                ('Os 3 do Nordeste', 'Forró', 'Atração confirmada no Maior São João do Mundo 2026.', '@os3donordeste'),
                                                                ('Elba Ramalho', 'Forró', 'Uma das maiores representantes da música nordestina e presença tradicional no São João de Campina Grande.', '@elbaramalho'),
                                                                ('Guilherme Dantas', 'Forró', 'Atração confirmada no Maior São João do Mundo 2026.', '@guilhermedantas'),
                                                                ('Lucy Alves', 'Forró', 'Cantora, atriz e multi-instrumentista paraibana.', '@lucyalves'),
                                                                ('Capilé', 'Forró', 'Artista tradicional dos festejos juninos paraibanos.', '@capile'),
                                                                ('Vicente Nery', 'Forró', 'Um dos grandes nomes do forró romântico.', '@vicentenery'),
                                                                ('José Augusto', 'Romântico', 'Cantor consagrado da música romântica brasileira.', '@joseaugusto'),
                                                                ('Waldonys', 'Forró', 'Cantor e sanfoneiro referência da música nordestina.', '@waldonys'),
                                                                ('Fabiana Souto', 'Forró', 'Atração confirmada no Maior São João do Mundo 2026.', '@fabianasouto'),
                                                                ('Japinha', 'Forró', 'Cantora conhecida nacionalmente pelo forró eletrônico.', '@japinha'),
                                                                ('Nuzio Medeiros', 'Forró', 'Atração confirmada no Maior São João do Mundo 2026.', '@nuziomedeiros'),
                                                                ('Kadu Martins', 'Forró', 'Cantor em destaque na nova geração do forró.', '@kadumartins'),
                                                                ('Jefferson Arretado', 'Forró', 'Artista paraibano presente na programação do evento.', '@jeffersonarretado'),
                                                                ('Xand Avião', 'Forró', 'Um dos maiores nomes da música nordestina contemporânea.', '@xandaviao'),
                                                                ('Nattan', 'Forró', 'Cantor de grande sucesso no cenário nacional.', '@nattan'),
                                                                ('Kátia e Aduílio', 'Forró', 'Dupla tradicional do forró pé de serra.', '@katiaeaduilio'),
                                                                ('Ranniery Gomes', 'Forró', 'Cantor paraibano presente na programação junina.', '@rannierygomes'),
                                                                ('Zé Vaqueiro', 'Forró', 'Um dos artistas mais populares do piseiro brasileiro.', '@zevaqueiro'),
                                                                ('Felipe Amorim', 'Forró', 'Cantor e compositor de destaque nacional.', '@felipeamorim'),
                                                                ('Talita Mel', 'Forró', 'Atração confirmada no Maior São João do Mundo 2026.', '@talitamel'),
                                                                ('Stella Alves', 'Forró', 'Cantora nordestina presente na programação.', '@stellaalves'),
                                                                ('Simone Mendes', 'Sertanejo', 'Uma das maiores vozes femininas do sertanejo atual.', '@simonemendes'),
                                                                ('Japãozin', 'Forró', 'Cantor de forró e piseiro em destaque nacional.', '@japaozin'),
                                                                ('Mara Pavanelly', 'Forró', 'Cantora consagrada do forró romântico.', '@marapavanelly'),
                                                                ('Nicácia Brasil', 'Forró', 'Atração confirmada no Maior São João do Mundo 2026.', '@nicaciabrasil'),
                                                                ('Forró Real', 'Forró', 'Banda tradicional do forró eletrônico.', '@forroreal'),
                                                                ('Bonde do Brasil', 'Forró', 'Banda conhecida pelo forró romântico.', '@bondedobrasil'),
                                                                ('Chambinho', 'Forró', 'Cantor e sanfoneiro nordestino.', '@chambinho'),
                                                                ('Diego Facó', 'Forró', 'Atração confirmada no Maior São João do Mundo 2026.', '@diegofaco'),
                                                                ('FHOP Music', 'Gospel', 'Ministério de louvor com projeção nacional.', '@fhopmusic'),
                                                                ('Eli Soares', 'Gospel', 'Um dos principais nomes da música gospel brasileira.', '@elisoares'),
                                                                ('Filho do Piseiro', 'Piseiro', 'Atração confirmada no Maior São João do Mundo 2026.', '@filhodopiseiro'),
                                                                ('Claudinei e Juliana', 'Forró', 'Dupla presente na programação junina.', '@claudineiejuliana'),
                                                                ('Eduardinho', 'Forró', 'Atração confirmada no Maior São João do Mundo 2026.', '@eduardinho'),
                                                                ('Forró Pegado', 'Forró', 'Banda de destaque no forró eletrônico.', '@forropegado'),
                                                                ('Sorriso Maroto', 'Pagode', 'Um dos maiores grupos de pagode do Brasil.', '@sorrisomaroto'),
                                                                ('Vitor Fernandes', 'Forró', 'Cantor de piseiro e forró em destaque nacional.', '@vitorfernandes'),
                                                                ('Mastruz com Leite', 'Forró', 'Banda histórica do forró brasileiro.', '@mastruzcomleite'),
                                                                ('Matheus Felipe', 'Forró', 'Atração confirmada no Maior São João do Mundo 2026.', '@matheusfelipe'),
                                                                ('Taty Girl', 'Forró', 'Uma das vozes femininas mais conhecidas do forró.', '@tatygirl'),
                                                                ('Márcia Fellipe', 'Forró', 'Cantora conhecida como a Fenomenal.', '@marciafellipe'),
                                                                ('Toca do Vale', 'Forró', 'Cantor e sanfoneiro tradicional do forró.', '@tocadovale'),
                                                                ('Atração Surpresa', 'Especial', 'Artista não divulgado pela organização do evento.', '@atracaosurpresa'),
                                                                ('Seu Desejo', 'Forró', 'Banda de grande sucesso no forró romântico.', '@seudesejo'),
                                                                ('Silvânia e Paulynho', 'Forró', 'Dupla formada por ex-integrantes de bandas tradicionais do forró.', '@silvaniaepaulynho'),
                                                                ('Mano Walter', 'Forró', 'Cantor conhecido pelos sucessos do forró de vaquejada.', '@manowalter'),
                                                                ('Fabricio Rodrigues', 'Forró', 'Atração confirmada no Maior São João do Mundo 2026.', '@fabriciorodrigues'),
                                                                ('Pablo', 'Arrocha', 'Conhecido nacionalmente como o Rei da Sofrência.', '@pablooficial'),
                                                                ('Rey Vaqueiro', 'Forró', 'Cantor em destaque no forró de vaquejada.', '@reyvaqueiro'),
                                                                ('Flávio José', 'Forró', 'Um dos maiores representantes do forró tradicional.', '@flaviojose'),
                                                                ('Yasmin Sensação', 'Forró', 'Cantora presente na programação do evento.', '@yasminsensacao'),
                                                                ('Sirano e Sirino', 'Forró', 'Dupla tradicional da música nordestina e da vaquejada.', '@siranoesirino'),
                                                                ('J Show e Chapéu Palha', 'Forró', 'Atração confirmada na programação de Galante.', '@jshowechapeupalha'),
                                                                ('Forró Medonho', 'Forró', 'Banda participante da programação dos distritos do São João.', '@forromedonho'),
                                                                ('Ferro na Boneca', 'Forró', 'Banda de forró eletrônico com destaque no Nordeste.', '@ferronaboneca'),
                                                                ('Collo de Menina', 'Forró', 'Banda tradicional do forró romântico.', '@collodemenina'),
                                                                ('Kally Silva', 'Forró', 'Cantora nordestina presente na programação de Galante.', '@kallysilva'),
                                                                ('Saulo Farra', 'Forró', 'Cantor participante da programação dos distritos do evento.', '@saulofarra'),
                                                                ('Kátia Cilene e Aduílio Mendes', 'Forró', 'Dupla tradicional do forró romântico presente na programação da Vila Sítio São João.', '@katiaecileneeaduiliomendes'),
                                                                ('Desejo de Menina', 'Forró', 'Uma das bandas mais conhecidas do forró romântico brasileiro.', '@desejodemenina'),
                                                                ('Luan Estilizado', 'Forró', 'Cantor e sanfoneiro destaque do forró contemporâneo.', '@luanestilizado'),
                                                                ('Lara Amélia', 'Forró', 'Cantora participante da programação da Vila Sítio São João.', '@laraamelia'),
                                                                ('Assum Preto', 'Forró', 'Banda tradicional do forró nordestino.', '@assumpreto'),
                                                                ('Jorge de Altinho', 'Forró', 'Cantor, compositor e sanfoneiro referência da música nordestina.', '@jorgedealtinho'),
                                                                ('Verônica Ryos e Banda', 'Forró', 'Atração confirmada na programação da Vila Sítio São João.', '@veronicaryos'),
                                                                ('Jeito Nordestino', 'Forró', 'Grupo musical participante dos festejos juninos.', '@jeitonordestino'),
                                                                ('Forró Campina', 'Forró', 'Banda regional presente na programação do evento.', '@forrocampina'),
                                                                ('Juzé', 'MPB', 'Cantor, compositor e ator paraibano.', '@juzeoficial'),
                                                                ('Assisão', 'Forró', 'Cantor e compositor consagrado da música nordestina.', '@assisao'),
                                                                ('Tropykália', 'Forró', 'Banda tradicional do forró eletrônico.', '@tropykalia'),
                                                                ('Donas da Farra', 'Forró', 'Grupo feminino participante da programação junina.', '@donasdafarra'),
                                                                ('Batista Lima', 'Forró', 'Cantor e compositor conhecido por sua trajetória no forró romântico.', '@batistalima'),
                                                                ('Santanna', 'Forró', 'Conhecido como O Cantador, um dos grandes nomes do forró tradicional.', '@santannaocantador')
